services:
  db:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - sample_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d mydatabase -h localhost"]
      interval: 5s
      retries: 10
  app:
    build: .
    container_name: fast_api
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    networks:
      - sample_network

  test:
    build: .
    command: pytest
    volumes:
      - .:/app
    depends_on:
      - db
    env_file:
      - .env

volumes:
  postgres_data:

networks:
  sample_network:
    driver: bridge